mysql:
  origin:
    host: mysql
    port: 3306
    user: root
    pass: 123456
    database: origin
    charset: utf8mb4
  format:
    gorm: "%s:%s@(%s:%s)/%s?charset=%s&parseTime=True&loc=Local"
    xorm: "%s:%s@tcp(%s:%s)/%s?charset=%s"

redis:
  host: redis
  port: 6379
  pass:
  db:

kafka:
  broker: 192.168.5.5:9092
  topic:
    task: task
    object: object

jwt:
  Issuer: origin
  SigningKey: authorization_key
  # ResetHour: 20
  # ExpireHour: 24
