rango:
  host: http://127.0.0.1:2020

jwt:
  token: authorization_token_key

mysql:
  golang:
    host: 192.168.5.5
    port: 3306
    user: root
    pass: secret20
    database: golang
    charset: utf8mb4
  model_gorm:
    dsn_format: "%s:%s@(%s:%s)/%s?charset=%s&parseTime=True&loc=Local"
  model_xorm:
    dsn_format: "%s:%s@tcp(%s:%s)/%s?charset=%s"

redis:
  host: 192.168.5.5
  port: 6379
  pass:
  db:

kafka:
  broker: 192.168.5.5:9092
  topic:
    task: task
    object: object
