// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/": {
            "get": {
                "description": "首页index入口，默认返回为一个index字符串",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api模块"
                ],
                "summary": "首页index",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/params/:id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api模块"
                ],
                "summary": "测试请求参数",
                "parameters": [
                    {
                        "description": "name入参，测试入参",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "响应的body体",
                        "schema": {
                            "type": "map"
                        }
                    }
                }
            }
        },
        "/use/logrus": {
            "get": {
                "description": "日志处理，详细使用方式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Log模块"
                ],
                "summary": "日志处理",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "map"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Params": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2020",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "rango 服务接口 Swagger 文档",
	Description:      "rango服务端接口文档，注意模块名称",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
