version: "3"

services:
  rango-prod:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    image: rango-prod
    container_name: rango-prod
    restart: always
    ports:
      - '90:80'
    volumes:
      - ../nginx/:/etc/nginx/conf.d/
      - ../../../aigc:/usr/share/nginx/html/aigc
